--liquibase formatted sql

--changeset Dmitry:1
CREATE TABLE employee(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(32) NOT NULL,
    last_name varchar(32) NOT NULL,
    birth_date date NOT NULL,
    department varchar(255) NOT NULL,
    salary real NOT NULL
)